# Generated by Django 5.0.7 on 2026-08-15 09:37

import django.core.files.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('operation', models.CharField(choices=[('pdf_to_word', 'PDF to Word'), ('pdf_to_excel', 'PDF to Excel'), ('pdf_to_pptx', 'PDF to PowerPoint'), ('pdf_to_jpg', 'PDF to JPG'), ('pdf_to_pdfa', 'PDF to PDF/A'), ('pdf_to_markdown', 'PDF to Markdown'), ('word_to_pdf', 'Word to PDF'), ('excel_to_pdf', 'Excel to PDF'), ('pptx_to_pdf', 'PowerPoint to PDF'), ('jpg_to_pdf', 'JPG to PDF'), ('html_to_pdf', 'HTML to PDF')], max_length=20)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('output_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/aman-srivastav/EDITDOCSNOW-BE/private_media'), upload_to='convert/output/')),
                ('output_is_zip', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdf_convert_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='pdf_convert_user_id_350d32_idx'), models.Index(fields=['status'], name='pdf_convert_status_0a9fea_idx'), models.Index(fields=['operation'], name='pdf_convert_operati_95dfcb_idx'), models.Index(fields=['created_at'], name='pdf_convert_created_0ace25_idx')],
            },
        ),
    ]
