# Generated by Django 5.0.7 on 2026-08-15 11:08

import apps.common.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(default='eng', max_length=40)),
                ('source_file', models.FileField(blank=True, null=True, storage=apps.common.storage.PrivateJobStorage(), upload_to='ocr/source/')),
                ('output_file', models.FileField(blank=True, null=True, storage=apps.common.storage.PrivateJobStorage(), upload_to='ocr/output/')),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('ocr_page_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdf_ocr_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='pdf_ocr_job_user_id_d4e74f_idx'), models.Index(fields=['status'], name='pdf_ocr_job_status_acdc0b_idx'), models.Index(fields=['created_at'], name='pdf_ocr_job_created_c9c727_idx')],
            },
        ),
    ]
