# Generated by Django 5.0.7 on 2026-08-15 07:49

import django.core.files.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageNumberJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('numbered_pages', models.JSONField(default=list)),
                ('start_number', models.IntegerField(default=1)),
                ('position', models.CharField(choices=[('top-left', 'Top left'), ('top-center', 'Top center'), ('top-right', 'Top right'), ('bottom-left', 'Bottom left'), ('bottom-center', 'Bottom center'), ('bottom-right', 'Bottom right')], default='bottom-center', max_length=20)),
                ('font_size', models.PositiveIntegerField(default=12)),
                ('font_color', models.CharField(default='#000000', max_length=7)),
                ('margin', models.FloatField(default=28.0)),
                ('prefix', models.CharField(blank=True, default='', max_length=40)),
                ('suffix', models.CharField(blank=True, default='', max_length=40)),
                ('output_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/aman-srivastav/EDITDOCSNOW-BE/private_media'), upload_to='page-numbers/output/')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_number_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdf_page_number_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='pdf_page_nu_user_id_0b04ca_idx'), models.Index(fields=['status'], name='pdf_page_nu_status_ab99ec_idx'), models.Index(fields=['created_at'], name='pdf_page_nu_created_4ad79f_idx')],
            },
        ),
    ]
