# Generated by Django 5.0.7 on 2026-08-14 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('source_pages', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(choices=[('all_pages', 'Every page as its own PDF'), ('ranges', 'Custom page ranges'), ('every_n', 'Split every N pages'), ('extract', 'Extract specific pages into one PDF')], max_length=20)),
                ('params', models.JSONField(default=dict)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='splits/output/')),
                ('is_zip', models.BooleanField(default=False)),
                ('output_filenames', models.JSONField(default=list)),
                ('output_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdf_split_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='pdf_split_j_user_id_bd02a9_idx'), models.Index(fields=['status'], name='pdf_split_j_status_3d109c_idx'), models.Index(fields=['created_at'], name='pdf_split_j_created_a4e90c_idx')],
            },
        ),
    ]
