# Generated by Django 5.0.7 on 2026-08-15 10:42

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_split', '0002_splitjob_owner_token_alter_splitjob_output_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitjob',
            name='output_file',
            field=models.FileField(blank=True, null=True, storage=apps.common.storage.PrivateJobStorage(), upload_to='splits/output/'),
        ),
    ]
