# Generated by Django 5.0.7 on 2026-08-14 21:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_merge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergejob',
            name='owner_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='mergejob',
            name='output_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/aman-srivastav/EDITDOCSNOW-BE/private_media'), upload_to='merges/output/'),
        ),
    ]
