# Generated by Django 5.0.7 on 2026-08-14 22:12

import django.core.files.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovePagesJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('source_page_count', models.PositiveIntegerField(default=0)),
                ('removed_pages', models.JSONField(default=list)),
                ('output_page_count', models.PositiveIntegerField(default=0)),
                ('output_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/aman-srivastav/EDITDOCSNOW-BE/private_media'), upload_to='remove_pages/output/')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remove_pages_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdf_remove_pages_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='pdf_remove__user_id_448366_idx'), models.Index(fields=['status'], name='pdf_remove__status_5e6e9f_idx'), models.Index(fields=['created_at'], name='pdf_remove__created_be8ac6_idx')],
            },
        ),
    ]
