# Generated by Django 6.0.7 on 2026-07-11 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='documents/original/')),
                ('edited_file', models.FileField(blank=True, null=True, upload_to='documents/edited/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('xlsx', 'XLSX')], db_index=True, default='pdf', max_length=10)),
                ('file_size', models.BigIntegerField(default=0)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(db_index=True)),
                ('text', models.TextField()),
                ('bbox', models.JSONField(help_text='PDF coordinates [x0, y0, x1, y1]')),
                ('font_name', models.CharField(blank=True, default='', max_length=255)),
                ('font_size', models.FloatField(default=12)),
                ('color', models.CharField(default='#000000', max_length=20)),
                ('is_bold', models.BooleanField(default=False)),
                ('is_italic', models.BooleanField(default=False)),
                ('has_link', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='docs_editor.document')),
            ],
            options={
                'db_table': 'document_blocks',
                'ordering': ['page_number', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user'], name='documents_user_id_816ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_status_f31a08_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='documents_created_3c6eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='documentblock',
            index=models.Index(fields=['document'], name='document_bl_documen_90ec03_idx'),
        ),
        migrations.AddIndex(
            model_name='documentblock',
            index=models.Index(fields=['page_number'], name='document_bl_page_nu_181b15_idx'),
        ),
        migrations.AddIndex(
            model_name='documentblock',
            index=models.Index(fields=['document', 'page_number'], name='document_bl_documen_45e65f_idx'),
        ),
    ]
