# Generated by Django 5.0.7 on 2026-08-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentblock',
            name='original_text',
            field=models.TextField(blank=True, default='', help_text='Text as originally extracted from the PDF, used to detect edited blocks'),
        ),
    ]
