# Generated by Django 5.0.7 on 2026-08-15 11:38

import apps.common.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_editor', '0002_documentblock_original_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='owner_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Bearer token for anonymous ownership - same shared model as every other job app (apps.common.ownership). Added after this editor's initial release, when every endpoint was open to anyone with the document's UUID; existing rows are backfilled by the migration that introduces this field.", max_length=64),
        ),
        migrations.CreateModel(
            name='DocumentObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(db_index=True, help_text='0-indexed, same convention as DocumentBlock')),
                ('object_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('rectangle', 'Rectangle'), ('ellipse', 'Ellipse'), ('line', 'Line'), ('arrow', 'Arrow'), ('path', 'Freehand path')], db_index=True, max_length=20)),
                ('z_index', models.IntegerField(default=0)),
                ('bbox', models.JSONField(blank=True, default=list, help_text='[x0, y0, x1, y1]')),
                ('points', models.JSONField(blank=True, default=list)),
                ('rotation', models.FloatField(default=0, help_text="Degrees, clockwise, about the object's own center")),
                ('opacity', models.FloatField(default=1.0, help_text='0 (invisible) to 1 (opaque)')),
                ('fill_color', models.CharField(blank=True, default='', help_text='Hex color, blank = no fill', max_length=9)),
                ('stroke_color', models.CharField(blank=True, default='#000000', max_length=9)),
                ('stroke_width', models.FloatField(default=1.0)),
                ('text_content', models.TextField(blank=True, default='')),
                ('font_family', models.CharField(choices=[('sans', 'Sans'), ('serif', 'Serif'), ('mono', 'Monospace')], default='sans', max_length=10)),
                ('font_size', models.FloatField(default=14)),
                ('is_bold', models.BooleanField(default=False)),
                ('is_italic', models.BooleanField(default=False)),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10)),
                ('image_file', models.FileField(blank=True, null=True, storage=apps.common.storage.PrivateJobStorage(), upload_to='editor-objects/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_objects', to='docs_editor.document')),
            ],
            options={
                'db_table': 'document_objects',
                'ordering': ['page_number', 'z_index', 'created_at'],
                'indexes': [models.Index(fields=['document'], name='document_ob_documen_0869a8_idx'), models.Index(fields=['document', 'page_number'], name='document_ob_documen_16f2dc_idx')],
            },
        ),
    ]
