# Generated by Django 5.0.7 on 2026-08-15 11:44

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_editor', '0004_backfill_owner_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='edited_file',
            field=models.FileField(blank=True, help_text="Private storage, unlike original_file - this is the user-edited output, downloadable only through the token-gated DocumentDownloadView, matching every other feature's output_file convention.", null=True, storage=apps.common.storage.PrivateJobStorage(), upload_to='documents/edited/'),
        ),
    ]
