# Generated by Django 5.0.7 on 2026-08-15 10:42

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_organize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizejob',
            name='output_file',
            field=models.FileField(blank=True, null=True, storage=apps.common.storage.PrivateJobStorage(), upload_to='organize/output/'),
        ),
    ]
