# Generated by Django 5.0.7 on 2026-08-15 08:03

import django.core.files.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(choices=[('high_quality', 'High quality'), ('recommended', 'Recommended'), ('high_compression', 'High compression'), ('maximum_compression', 'Maximum compression')], default='recommended', max_length=24)),
                ('original_size', models.PositiveIntegerField(default=0)),
                ('compressed_size', models.PositiveIntegerField(default=0)),
                ('output_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/aman-srivastav/EDITDOCSNOW-BE/private_media'), upload_to='compress/output/')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compress_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdf_compress_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='pdf_compres_user_id_166957_idx'), models.Index(fields=['status'], name='pdf_compres_status_e37922_idx'), models.Index(fields=['created_at'], name='pdf_compres_created_cd35e0_idx')],
            },
        ),
    ]
