# Generated by Django 5.0.7 on 2026-08-15 09:17

import django.core.files.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('operation', models.CharField(choices=[('compress', 'Compress')], default='compress', max_length=20)),
                ('options', models.JSONField(default=dict)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('output_zip', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/aman-srivastav/EDITDOCSNOW-BE/private_media'), upload_to='batch/output/')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial (some files failed)'), ('failed', 'Failed (all files failed)')], db_index=True, default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdf_batch_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchFileJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('source_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/aman-srivastav/EDITDOCSNOW-BE/private_media'), upload_to='batch/source/')),
                ('output_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/aman-srivastav/EDITDOCSNOW-BE/private_media'), upload_to='batch/output/')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('original_size', models.PositiveIntegerField(default=0)),
                ('compressed_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pdf_batch.batchjob')),
            ],
            options={
                'db_table': 'pdf_batch_file_jobs',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['user'], name='pdf_batch_j_user_id_388d35_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['status'], name='pdf_batch_j_status_f9f77b_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['created_at'], name='pdf_batch_j_created_41315f_idx'),
        ),
        migrations.AddIndex(
            model_name='batchfilejob',
            index=models.Index(fields=['batch'], name='pdf_batch_f_batch_i_55bca8_idx'),
        ),
        migrations.AddIndex(
            model_name='batchfilejob',
            index=models.Index(fields=['status'], name='pdf_batch_f_status_36887b_idx'),
        ),
    ]
