# Generated by Django 5.0.7 on 2026-08-15 10:42

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_batch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchfilejob',
            name='output_file',
            field=models.FileField(blank=True, null=True, storage=apps.common.storage.PrivateJobStorage(), upload_to='batch/output/'),
        ),
        migrations.AlterField(
            model_name='batchfilejob',
            name='source_file',
            field=models.FileField(blank=True, null=True, storage=apps.common.storage.PrivateJobStorage(), upload_to='batch/source/'),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='output_zip',
            field=models.FileField(blank=True, null=True, storage=apps.common.storage.PrivateJobStorage(), upload_to='batch/output/'),
        ),
    ]
